### ISSUE TITLE
[BUG] Graves not generating 

### ISSUE THREAD

**Issue by YumatanGames** [ginsm/forgotten-graves#27] opened 2021-12-12 19:59 UTC
**Describe the bug**
I was playing on a server with a friend. We were roaming around really low in some cave and he died. And although he received the message stating that his grave were generating and the coords to find it, there were no grave where he died. I later used Replay Mod to be sure that it wasn't a mistake on our part, but indeed his grave weren't generated.  He lost all of his items.

I believe this was due to the fact we were bellow Y=0. But I didn't test it yet.

**Forgotten Graves Version**
v2.1.0-mc1.18

**To Reproduce**
I would try to die bellow Y=0

**Expected behavior**
I expected a Grave to be generated 

**Additional context**
We are using some extra mods. One that might be related is Terralith 2.0 I could also provide a list of the mods the server has if you want to, just let me know.

**Comment by ginsm** [comment] 2021-12-13 06:35
Sorry to hear that!

I tried to do some testing to figure out why this happened but to no avail. `v2.1.0-mc1.18` should spawn graves from levels `y-64` to `y319` (and spawn them at `y-60` if the death occurs below `y-64`), which is what was happening during my testing.

Could you share the exact coordinates he died, and what the cause of death was? Maybe send a screenshot of the area he died in as well? And if possible, a mod list would be appreciated. I'd like to try and recreate the scenario the best I can -- if you have it on replay mod and could make a clip, that'd be even better.

**Comment by YumatanGames** [comment] 2021-12-19 12:52
I'll try to send you all this info. Sorry for the late response... No free time, unfortunately.

**Comment by YumatanGames** [comment] 2021-12-19 13:22
[Server ModList.txt](https://github.com/ginsm/forgotten-graves/files/7740825/Server.ModList.txt)
[Client Mod list.txt](https://github.com/ginsm/forgotten-graves/files/7740826/Client.Mod.list.txt)

https://user-images.githubusercontent.com/80188726/146676342-5176748f-eecd-4f1b-a10c-48d1bd949b83.mp4

Coords: x:2513 y:-28 z:-2800

**Comment by ginsm** [comment] 2022-02-17 01:01
My bad, I never got around to testing this with the mods you were using. Did you ever get around to testing if it occurred every time for you with those mods?

**Comment by ginsm** [comment] 2022-02-25 06:31
I'm going to close this for now -- but if it's still occurring with the newer versions please feel free to reopen it, thanks!

**Closed by ginsm** 2022-02-25 06:31 UTC
Labels: bug
