### ISSUE TITLE
graves wipe items in inventory[BUG]

### ISSUE THREAD

**Issue by DarkestTTV** [ginsm/forgotten-graves#46] opened 2022-12-30 04:04 UTC
**Describe the bug**
When I use a grave to get items while having items in my inventory already, it gets rid of all the items in my inventory and adds the items that were in the grave

**Forgotten Graves Version**
forgottengraves-1.18.2-2.6.0

**To Reproduce**
1. Have items in inventory
2. Use grave from an earlier death
3. All items in inventory before using grave are gone

**Expected behavior**
The grave giving me my death items while keeping the items i already had in my inventory

**Comment by ginsm** [comment] 2022-12-30 06:57
Hey there, can you answer a few questions for me:

----

**Are you using any additional mods? If so, which?** 
**What does your configuration file look like?**
**Do you have any logs from when this occurred?** 
**Do you have a video/replay mod clip?**

*Upload any logs/config files you have to a site like pastebin and paste the link(s).*

----

The way this mod typically handles this problem in this way:
1. Store the inventory you had while retrieving the grave in a list.
2. Restore your inventory to how it was when the grave was generated.
3. Merge the items you had while retrieving the grave (from step 1) into any empty slots.
4. Drop any items that could not be merged (due to not having enough inventory space).

I just tested it in game and that's the behavior I saw following the reproduction steps given _(1.18.2-2.6.0)_. I tried a few other things as well to no avail (completely full inventories, partially full inventories, mixing and matching, etc). 

It's quite strange that you're seeing different behavior, but if you can answer the above questions it should give me a better idea of what is happening and how to help resolve the issue. Thanks!

**Closed** 2023-01-19 08:09 UTC
Labels: bug
