### ISSUE TITLE
[Crash] New placement feature isn't improved

### ISSUE THREAD

**Issue by A5ho9999** [ginsm/forgotten-graves#85] opened 2023-11-07 09:13 UTC
**Describe the bug**
The new placement is replacing blocks and crashing when can't be placed (wasn't an issue until new placement)

Full Log: https://gist.github.com/A5ho9999/4aaa1f160f484b1f2ca1275bbd78bd12

**Forgotten Graves Version**
Forgotten Graves 1.20.1-3.2.3

**To Reproduce**
1. Go to end
2. Jump into void
3. Crash

**Expected behavior**
Not replace blocks and just place in air + not crashing the game

**Additional context**
```
	at net.minecraft.class_1937.method_8320(class_1937.java:16551)
	at me.mgin.graves.block.utility.PlaceGrave.spawnGrave(PlaceGrave.java:217)
	at me.mgin.graves.block.utility.PlaceGrave.place(PlaceGrave.java:62)
	at net.minecraft.class_1657.redirect$gci000$forgottengraves$dropAll(class_1657.java:18900)
	at net.minecraft.class_1657.method_16078(class_1657.java:683)
	at net.minecraft.class_1309.method_16080(class_1309.java:1413)
	at net.minecraft.class_3222.method_6078(class_3222.java:643)
	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
	at net.minecraft.class_1657.method_5643(class_1657.java:928)
	at net.minecraft.class_3222.method_5643(class_3222.java:732)
	at net.minecraft.class_1309.method_5825(class_1309.java:1876)
	at net.minecraft.class_1297.method_31473(class_1297.java:553)
	at net.minecraft.class_1297.method_5670(class_1297.java:536)
	at net.minecraft.class_1309.method_5670(class_1309.java:367)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.mixinextras$bridge$method_14226$273(class_3244.java)
	at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickPlayer$notTheCauseOfTickLag(NeruinaTickHandler.java:59)
	at net.minecraft.class_3244.wrapOperation$iel000$neruina$catchTickingPlayer(class_3244.java:9955)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
```

**Screenshots**
Replaced block on ground instead of placing on block
![placement](https://cdn.discordapp.com/attachments/1126325391460675681/1169055315967357048/2023-10-31_19.23.25.png?ex=6554029b&is=65418d9b&hm=c81c1c8aad458b59626bac71270cd80fd06653dd56da4e0023026890fa030d6a&)

**Comment by ginsm** [comment] 2023-11-07 09:44
Thanks for the report! I'm publishing v3.2.4 to Modrinth and CurseForge now which should fix the crash.

Are you able to reproduce it replacing blocks as opposed to finding a better spot to spawn? :thinking: If so, what steps were you taking? I've been unable to reproduce it when it comes to things like half slabs, path blocks, soul sand, torches, fences, etc.

**Comment by A5ho9999** [comment] 2023-11-07 10:42
Yup, if you have a platform (with nothing under it) and torches on top, dying on it with something like a torch. it replaces the block under

![1](https://cdn.discordapp.com/attachments/726977741424951416/1171398651499786241/2023-11-07_21.09.17.png?ex=655c8902&is=654a1402&hm=eb40658bb63ea581b926a3031d9c61b04e502868ae6a7529a1853a0068341c89&)

![2](https://cdn.discordapp.com/attachments/726977741424951416/1171399047257534475/2023-11-07_21.10.26.png?ex=655c8960&is=654a1460&hm=6d587fc10c00415bdd248842849abb68ec36103668bd084809911cc2f34d96d1&)

**Comment by ginsm** [comment] 2023-11-08 06:24
Awesome, that should make it easier to sort out, thanks. :grin:

**Comment by ginsm** [comment] 2023-11-19 11:16
`v3.2.5` should fix the issue where blocks were getting replaced so I'm going to close this issue for now. If you find some other edge case where blocks are getting replaced, please let me know, thanks! :grin:

**Closed by ginsm** 2023-11-19 11:16 UTC
Labels: bug
